"""Dice engine for checks, combat, and generated encounters."""

import random
import re
from typing import Dict, List


DICE_PATTERN = re.compile(r"^(?P<count>\d*)d(?P<sides>\d+)(?P<modifier>[+-]\d+)?$", re.I)


def normalize_damage_expression(value, default: str = "1d4") -> str:
    """Return a valid dice expression for damage/healing values.

    Existing dice expressions are preserved. A fixed positive integer is converted
    to one die with that many sides, so generated `6` becomes `1d6` instead of
    deterministic 6 damage. Zero remains `0` for non-damaging effects.
    """
    if value is None:
        return default
    cleaned = str(value).replace(" ", "").lower()
    if cleaned in {"", "none"}:
        return default
    if cleaned == "0":
        return "0"
    if DICE_PATTERN.match(cleaned):
        return cleaned
    if cleaned.isdigit():
        amount = int(cleaned)
        if amount <= 0:
            return "0"
        return f"1d{max(2, amount)}"
    return default


def roll(expression: str = "1d20") -> Dict:
    cleaned = str(expression).replace(" ", "").lower()
    # Damage data generated by older saves may still contain fixed integers.
    # Convert those to dice before resolving so damage is never deterministic.
    if cleaned.isdigit() and int(cleaned) > 0:
        cleaned = normalize_damage_expression(cleaned)
    match = DICE_PATTERN.match(cleaned)
    if not match:
        raise ValueError(f"Invalid dice expression: {expression}")

    count = int(match.group("count") or 1)
    sides = int(match.group("sides"))
    modifier = int(match.group("modifier") or 0)

    if count < 1 or count > 100 or sides < 2 or sides > 1000:
        raise ValueError("Dice expression is outside supported limits")

    rolls: List[int] = [random.randint(1, sides) for _ in range(count)]
    total = sum(rolls) + modifier

    return {
        "expression": cleaned,
        "rolls": rolls,
        "modifier": modifier,
        "total": total,
        "natural_1": count == 1 and sides == 20 and rolls[0] == 1,
        "natural_20": count == 1 and sides == 20 and rolls[0] == 20,
    }
